eDoc/eDoc.Web/Controllers/AdminDocumentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eDoc.Models;
using eDoc.Data;

namespace eDoc.Web.Controllers
{
    [Authorize(Roles="Admin")]
    public class AdminDocumentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /AdminDocuments/
        public ActionResult Index()
        {
            var documents = db.Documents.Include(d => d.Author);
            return View(documents.ToList());
        }

        // GET: /AdminDocuments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            return View(document);
        }

        // GET: /AdminDocuments/Create
        public ActionResult Create()
        {
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "UserName");
            return View();
        }

        // POST: /AdminDocuments/Create
		// To protect from over posting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		// 
		// Example: public ActionResult Update([Bind(Include="ExampleProperty1,ExampleProperty2")] Model model)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Document document)
        {
            if (ModelState.IsValid)
            {
                db.Documents.Add(document);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AuthorId = new SelectList(db.Users, "Id", "UserName", document.AuthorId);
            return View(document);
        }

        // GET: /AdminDocuments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "UserName", document.AuthorId);
            return View(document);
        }

        // POST: /AdminDocuments/Edit/5
		// To protect from over posting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		// 
		// Example: public ActionResult Update([Bind(Include="ExampleProperty1,ExampleProperty2")] Model model)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Document document)
        {
            if (ModelState.IsValid)
            {
                db.Entry(document).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "UserName", document.AuthorId);
            return View(document);
        }

        // GET: /AdminDocuments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            return View(document);
        }

        // POST: /AdminDocuments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Document document = db.Documents.Find(id);
            db.Documents.Remove(document);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

eDoc/eDoc.Web/Views/Admin/Answer.cshtml
@model eDoc.Web.ViewModels.DocumentIndexVM

@{
    ViewBag.Title = "Answer";
}

<h2>Отговори</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @Html.HiddenFor(model => model.Id)

    <div>
        <label>Статус: </label>
        <select name="status">
            @foreach (var status in ViewBag.Statuses)
            {
                <option value="@status.Id">@status.Name</option>
            }
        </select>
    </div>
    
    <div style="width:300px">
        <label>Коментар:</label>
        <textarea name="comment" rows="10" cols="80" style="width:auto"></textarea>
    </div>
    <div class="form-actions no-color">
        <input type="submit" value="Запази промените" class="btn" />
    </div>
}

eDoc/eDoc.Web/Views/Admin/Index.cshtml
@model eDoc.Web.ViewModels.DocumentIndexVM

@{
    ViewBag.Title = "Answer";
}
<style>
    li {
        margin-top: 5px;
    }
</style>
<h2>Администрация</h2>
<ul>
    <li>@Html.ActionLink("Документи", "Index", "AdminDocuments", null, new { @class = "btn" }) <br /></li>
    <li>@Html.ActionLink("Потребители", "Index", "AdminUsers", null, new { @class = "btn" })     <br />   </li>
    <li>@Html.ActionLink("Настройки на системата", "Settings", "Admin", null, new { @class = "btn" }) <br /></li>
</ul>

eDoc/eDoc.Web/Views/Admin/Settings.cshtml
@{
    ViewBag.Title = "Settings";
}

<h2>Настройки</h2>

@using (Html.BeginForm())
{
    <label for="emailSetting">Валидация по Email</label>
    <input type="checkbox" name="emailSetting" id="emailSetting" checked="@Settings.ValidateEmail"/>
    
    <label for="smsSetting">Валидация по SMS</label>
    <input type="checkbox" name="phoneSetting" id="smsSetting" checked="@Settings.ValidateSms" />

    <label for="tokenSetting">Валидация по Token</label>
    <input type="checkbox" name="tokenSetting" id="tokenSetting" checked="@Settings.ValidateToken" />

    <div class="form-actions no-color">
        <input type="submit" value="Запази" class="btn" />
    </div>
}