eDoc/eDoc.Web/Controllers/AdminDocumentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eDoc.Models;
using eDoc.Data;

namespace eDoc.Web.Controllers
{
    [Authorize(Roles="Admin")]
    public class AdminDocumentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /AdminDocuments/
        public ActionResult Index()
        {
            var documents = db.Documents.Include(d => d.Author);
            return View(documents.ToList());
        }

        // GET: /AdminDocuments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            return View(document);
        }

        // GET: /AdminDocuments/Create
        public ActionResult Create()
        {
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "UserName");
            return View();
        }

        // POST: /AdminDocuments/Create
		// To protect from over posting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		// 
		// Example: public ActionResult Update([Bind(Include="ExampleProperty1,ExampleProperty2")] Model model)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Document document)
        {
            if (ModelState.IsValid)
            {
                db.Documents.Add(document);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AuthorId = new SelectList(db.Users, "Id", "UserName", document.AuthorId);
            return View(document);
        }

        // GET: /AdminDocuments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "UserName", document.AuthorId);
            return View(document);
        }

        // POST: /AdminDocuments/Edit/5
		// To protect from over posting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		// 
		// Example: public ActionResult Update([Bind(Include="ExampleProperty1,ExampleProperty2")] Model model)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Document document)
        {
            if (ModelState.IsValid)
            {
                db.Entry(document).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "UserName", document.AuthorId);
            return View(document);
        }

        // GET: /AdminDocuments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            return View(document);
        }

        // POST: /AdminDocuments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Document document = db.Documents.Find(id);
            db.Documents.Remove(document);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

eDoc/eDoc.Web/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Net.Http;
using System.Web.Mvc;
using eDoc.Models;
using eDoc.Data;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using eDoc.Web.ViewModels;
using Typesafe.Mailgun;
using System.Net.Mail;
using System.Data.Entity.Validation;

namespace eDoc.Web.Controllers
{
    public class DocumentController : BaseController
    {
        public ActionResult Index()
        {
            if (this.User.IsInRole("Admin"))
            {
                // TODO: Fix. Not good!
                var docs = this.Data.Documents.All().ToList().Where(x => Settings.Validate(x) && x.StatusId == 2).ToList();
                return View(GetDocumentsAsVM(docs.AsQueryable()));
            }

            var userId = this.User.Identity.GetUserId();
            var allDocsOfCurrUser = this.Data.Documents.All().Where(x => x.AuthorId == userId);
            return View(GetDocumentsAsVM(allDocsOfCurrUser));
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Document document = this.Data.Documents.GetById((int)id);
            if (document == null)
            {
                return HttpNotFound();
            }

            return View(GetDocumentAsVM(document));
        }

        [HttpGet]
        public ActionResult SelectType(string type)
        {
            return PartialView("_" + type);
        }

        public ActionResult Create()
        {
            ViewBag.DocumentTypes = this.Data.DocumentTypes.All().ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string content, int type, string title)
        {
            if (ModelState.IsValid)
            {
                if (this.User.Identity.IsAuthenticated)
                {
                    string userId = this.User.Identity.GetUserId();

                    var user = this.Data.Users.All().FirstOrDefault(x => x.Id == userId);
                    Document docToAdd = new Document
                    {
                        Author = user,
                        Date = DateTime.Now,
                        Content = content,
                        Type = this.Data.DocumentTypes.GetById(type),
                        Status = this.Data.Statuses.All().FirstOrDefault(s => s.Name.ToLower() == "pending"),
                        PhoneCode = Utils.GetConfirmationCode("phone" + user.UserName, 8),
                        EmailCode = Utils.GetConfirmationCode("email" + user.UserName, 8),
                    };

                    if (Settings.ValidateToken)
                    {
                        docToAdd.TokenInput = Utils.GetConfirmationCode("token" + user.UserName, 8);
                        docToAdd.TokenCode = Utils.GetTokenConfirmationCode(user.UserName, docToAdd.TokenInput);
                    }

                    this.Data.Documents.Add(docToAdd);
                    this.Data.SaveChanges();
                    try
                    {
                        if (Settings.ValidateSms)
                            Utils.SendSms(user.PhoneNumber, @"Document #" + docToAdd.Id + ": confirmation code is " + docToAdd.PhoneCode + ".");

                        if (Settings.ValidateEmail)
                            Utils.SendEmail(user.Email, "Confirm document #" + docToAdd.Id,
                                "Your confirmation code for document #" + docToAdd.Id + " is " + docToAdd.EmailCode + ".");
                    }
                    catch
                    {
                        this.Data.SaveChanges();
                        this.Data.Documents.Delete(docToAdd);
                        throw;
                    }
                }
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult EmailVerify(string code, int documentId)
        {
            var doc = this.Data.Context.Documents.Find(documentId);

            if (doc.EmailCode == code)
            {
                doc.EmailValidated = true;
            }

            this.Data.SaveChanges();

            return RedirectToAction("Details", new { id = documentId });
        }

        [HttpPost]
        public ActionResult GsmVerify(string code, int documentId)
        {
            var doc = this.Data.Documents.GetById(documentId);

            if (doc.PhoneCode == code)
            {
                doc.PhoneValidated = true;
            }
            this.Data.SaveChanges();

            return RedirectToAction("Details", new { id = documentId });
        }


        [HttpPost]
        public ActionResult TokenVerify(string code, int documentId)
        {
            var doc = this.Data.Documents.GetById(documentId);

            if (doc.TokenCode == code)
            {
                doc.TokenValidated = true;
            }
            this.Data.SaveChanges();

            return RedirectToAction("Details", new { id = documentId });
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Document document = this.Data.Documents.GetById((int)id);
            if (document == null)
            {
                return HttpNotFound();
            }

            ViewBag.DocumentTypes = this.Data.DocumentTypes.All().ToList();
            ViewBag.Statuses = this.Data.Statuses.All().ToList();

            return View(GetDocumentAsVM(document));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(DocumentEditVM document)
        {
            if (ModelState.IsValid)
            {
                var currentDocument = this.Data.Documents.GetById(document.Id);
                currentDocument.Content = document.Content;
                currentDocument.Status = this.Data.Statuses.GetById(document.Status);
                currentDocument.Type = this.Data.DocumentTypes.GetById(document.Type);
                this.Data.Documents.Update(currentDocument);
                this.Data.SaveChanges();
                return RedirectToAction("Index");
            }

            return View("Index");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Document document = this.Data.Documents.GetById((int)id);
            if (document == null)
            {
                return HttpNotFound();
            }

            return View(GetDocumentAsVM(document));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Document document = this.Data.Documents.GetById((int)id);
            this.Data.Documents.Delete(document);
            this.Data.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

eDoc/eDoc.Web/Views/AdminDocuments/Create.cshtml
@model eDoc.Models.Document

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="form-horizontal">
        <legend>Document @Model.Id</legend>

        <div class="control-group">
            @Html.LabelFor(model => model.Date, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Date)
                @Html.ValidationMessageFor(model => model.Date, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.Content, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Content)
                @Html.ValidationMessageFor(model => model.Content, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.AuthorId, "AuthorId", new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownList("AuthorId", String.Empty)
                @Html.ValidationMessageFor(model => model.AuthorId, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.PhoneValidated, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.PhoneValidated)
                @Html.ValidationMessageFor(model => model.PhoneValidated, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.EmailValidated, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.EmailValidated)
                @Html.ValidationMessageFor(model => model.EmailValidated, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.PhoneCode, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.PhoneCode)
                @Html.ValidationMessageFor(model => model.PhoneCode, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.EmailCode, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.EmailCode)
                @Html.ValidationMessageFor(model => model.EmailCode, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.TokenInput, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.TokenInput)
                @Html.ValidationMessageFor(model => model.TokenInput, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.TokenCode, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.TokenCode)
                @Html.ValidationMessageFor(model => model.TokenCode, null, new { @class = "help-inline" })
            </div>
        </div>

     

        <div class="control-group">
            @Html.LabelFor(model => model.Comment, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Comment)
                @Html.ValidationMessageFor(model => model.Comment, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="form-actions no-color">
            <input type="submit" value="Create" class="btn" />
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eDoc/eDoc.Web/Views/AdminDocuments/Delete.cshtml
@model eDoc.Models.Document

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Document @Model.Id</legend>

    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.Author.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneValidated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneValidated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailValidated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailValidated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TokenInput)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TokenInput)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TokenCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TokenCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

    </dl>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>
}

eDoc/eDoc.Web/Views/AdminDocuments/Details.cshtml
@model eDoc.Models.Document

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Document @Model.Id</legend>
    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.Author.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneValidated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneValidated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailValidated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailValidated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TokenInput)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TokenInput)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TokenCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TokenCode)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

    </dl>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

eDoc/eDoc.Web/Views/AdminDocuments/Edit.cshtml
@model eDoc.Models.Document

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="form-horizontal">
        <legend>Document @Model.Id</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="control-group">
            @Html.LabelFor(model => model.Date, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Date)
                @Html.ValidationMessageFor(model => model.Date, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.Content, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Content)
                @Html.ValidationMessageFor(model => model.Content, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.AuthorId, "AuthorId", new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownList("AuthorId", String.Empty)
                @Html.ValidationMessageFor(model => model.AuthorId, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.PhoneValidated, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.PhoneValidated)
                @Html.ValidationMessageFor(model => model.PhoneValidated, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.EmailValidated, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.EmailValidated)
                @Html.ValidationMessageFor(model => model.EmailValidated, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.PhoneCode, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.PhoneCode)
                @Html.ValidationMessageFor(model => model.PhoneCode, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.EmailCode, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.EmailCode)
                @Html.ValidationMessageFor(model => model.EmailCode, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.TokenInput, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.TokenInput)
                @Html.ValidationMessageFor(model => model.TokenInput, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.TokenCode, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.TokenCode)
                @Html.ValidationMessageFor(model => model.TokenCode, null, new { @class = "help-inline" })
            </div>
        </div>


        <div class="control-group">
            @Html.LabelFor(model => model.Comment, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Comment)
                @Html.ValidationMessageFor(model => model.Comment, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="form-actions no-color">
            <input type="submit" value="Save" class="btn" />
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eDoc/eDoc.Web/Views/AdminDocuments/Index.cshtml
@model IEnumerable<eDoc.Models.Document>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            #
        </th>
        <th>
            Автор
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneValidated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailValidated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TokenInput)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TokenCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comment)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneValidated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailValidated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TokenInput)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TokenCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
            <td>
                @Html.ActionLink("Редактирай", "Edit", "Document", new { id = item.Id }, null) |
                @Html.ActionLink("Детайли", "Details", "Document", new { id = item.Id }, null) |
                @Html.ActionLink("Изтрий", "Delete", "Document", new { id = item.Id }, null)
            </td>
        </tr>
    }

</table>